from __future__ import annotations
import os, sys
import hashlib


# Get the directory of the current file
current_dir = os.path.dirname(os.path.abspath(__file__))

# Construct the path to the utilities module
utilities_path = os.path.join(current_dir, "../../sphinx_ext/")
sys.path.append(utilities_path)


from make_docs_utilities import get_all_code_blocks, pushd


def hash_code_block(code: str, language: str) -> str:
    return hashlib.md5(
        (code.strip() + "-" + language.strip()).encode("utf-8")
    ).hexdigest()


try:
    with pushd(__file__):
        all_code_blocks = get_all_code_blocks()

        with open("docs_examples_output.py", "w") as f:
            # First write the pre-amble to the file
            f.write("# This file is generated by the build_docs_preview.py script\n")
            f.write("# It should be used by the docs preview site\n")

            # Now write some common components we're going to use
            with open("docs_preview_setup.py", "r") as setup_file:
                setup_code = setup_file.read()
                f.write(setup_code)
                f.write("\n\n")

            # Now iterate through all of the code blocks, and write them in a single block

            def write_code_block(code_block: str):
                # We need to wrap the code block in a live preview function
                code_block = code_block.strip()
                hash = hash_code_block(code_block, "python")

                f.write(f'doc_{hash} = ui_live_result("""\n')
                f.write(code_block.replace('"""', '\\"\\"\\"') + "\n")
                f.write('\n""")\n')
                f.write("\n")

            for file_code_blocks in all_code_blocks:
                for code_block in file_code_blocks:
                    write_code_block(code_block)
                    f.write("\n")
except Exception:
    sys.exit(1)
